// DIBUAT OTOMATIS oleh `npm run tarif:sumber` dari scripts/data/tarif-resmi.json. Jangan diubah langsung.
// Petunjuk dasar hukum & sumber per kab/kota untuk AI tarif (AGENTS.md 1.8 C); tanpa angka tarif.

export const PETUNJUK_TARIF = {
  "Makassar": "Perda Kota Makassar No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://bapenda.makassarkota.go.id/wp-content/uploads/2024/08/PERDA-NOMOR-1-TAHUN-2024-TENTANG-PDRD.pdf",
  "Gowa": "Perda Kab. Gowa No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/307322/perda-kab-gowa-no-1-tahun-2024",
  "Maros": "Perda Kab. Maros No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/307602/perda-kab-maros-no-1-tahun-2024",
  "Takalar": "Perda Kab. Takalar No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/293053/perda-kab-takalar-no-1-tahun-2024",
  "Pangkep": "Perda Kab. Pangkajene dan Kepulauan No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/331987",
  "Barru": "Perda Kab. Barru No. 3 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/280410/perda-kab-barru-no-03-tahun-2023",
  "Parepare": "Perda Kota Parepare No. 12 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://jdih.pareparekota.go.id/?p=8465",
  "Sidrap": "Perda Kab. Sidenreng Rappang No. 4 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://sidrapkab.go.id/site/dokumendaerah/detail/Dokumen053436-Perda-No-4-Tahun-2023-tentang-Pajak-Daerah-dan-Retribusi-Daerah",
  "Pinrang": "Perda Kab. Pinrang No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/309627/perda-kab-pinrang-no-1-tahun-2024",
  "Enrekang": "Perda Kab. Enrekang No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/303130/perda-kab-enrekang-no-1-tahun-2024",
  "Tana Toraja": "Perda Kab. Tana Toraja No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah (perlu dipastikan)",
  "Toraja Utara": "Perda Kab. Toraja Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah (perlu dipastikan); sumber: https://bapenda.torajautarakab.go.id/dasar-hukum/",
  "Luwu Timur": "Perda Kab. Luwu Timur No. 9 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-luwu-timur-9-2023",
  "Luwu Utara": "Perda Kab. Luwu Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://jdih.luwuutarakab.go.id/uploads/produk_hukum/Produk-Hukum-1-1725604986.pdf",
  "Luwu": "Perda Kab. Luwu No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://jdih.luwukab.go.id/dokumen/view?id=717",
  "Soppeng": "Perda Kab. Soppeng No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-soppeng-no-1-tahun-2024",
  "Bone": "Perda Kab. Bone No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah (perlu dipastikan)",
  "Sinjai": "Perda Kab. Sinjai No. 3 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/286166/perda-kab-sinjai-no-3-tahun-2023",
  "Bulukumba": "Perda Kab. Bulukumba No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah (perlu dipastikan)",
  "Bantaeng": "Perda Kab. Bantaeng No. 3 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/279880/perda-kab-bantaeng-no-3-tahun-2023",
  "Jeneponto": "Perda Kab. Jeneponto No. 7 Tahun 2023 tentang Pajak dan Retribusi Daerah; sumber: https://www.scribd.com/document/702118699/Perda-Nomor-7-Tahun-2023-Tentang-Pajak-Dan-Retribusi-Daerah-Kabupaten-Jeneponto-Ok-Fix",
  "Mamuju Tengah": "Perda Kab. Mamuju Tengah No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/296996/perda-kab-mamuju-tengah-no-1-tahun-2024",
  "Pasangkayu": "Perda Kab. Pasangkayu No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/296989/perda-kab-pasangkayu-no-1-tahun-2024",
  "Mamuju": "Perda Kab. Mamuju No. 10 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/288288/perda-kab-mamuju-no-10-tahun-2023",
  "Majene": "Perda Kab. Majene No. 1 Tahun 2024 tentang Pajak dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/299282/perda-kab-majene-no-1-tahun-2024",
  "Polewali Mandar": "Perda Kab. Polewali Mandar No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/293921/perda-kab-polewali-mandar-no-1-tahun-2024",
  "Mamasa": "Perda Kab. Mamasa No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/293432/perda-kab-mamasa-no-1-tahun-2024",
  "Palu": "Perda Kota Palu No. 9 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://perpajakan.ddtc.co.id/id/sumber-hukum/peraturan-daerah/perda-kota-palu-9-tahun-2023",
  "Donggala": "Perda Kab. Donggala No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/311064/perda-kab-donggala-no-1-tahun-2024",
  "Sigi": "Perda Kab. Sigi No. 11 Tahun 2023 tentang Pajak dan Retribusi Daerah (perlu dipastikan); sumber: https://jdih.sigikab.go.id/Peraturan/searching/?id_peraturan_cat=83",
  "Tojo Una-Una": "Perda Kab. Tojo Una-Una No. 9 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah, diubah Perda No. 1 Tahun 2026; sumber: https://sulteng.bpk.go.id/kabupaten-tojo-una-una/",
  "Morowali Utara": "Perda Kab. Morowali Utara No. 9 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah, diubah Perda No. 1 Tahun 2025; sumber: https://pasal.id/peraturan/perda/perda-kab-morowali-utara-9-2023",
  "Morowali": "Perda Kab. Morowali No. 17 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah",
  "Banggai": "Perda Kab. Banggai No. 5 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Download/366771/Perbup%20Banggai_21_2024_Peraturan%20Pelaksanaan%20Perda%20No%205%20Tahun%202023%20tentang%20Pajak%20Daerah%20dan%20Retribusi%20Daerah.pdf",
  "Toli-Toli": "Perda Kab. Tolitoli No. 9 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah, diubah Perda No. 1 Tahun 2026; sumber: https://infoperaturan.id/jdih/peraturan-daerah-kabupaten-tolitoli-nomor-9-tahun-2023/",
  "Kendari": "Perda Kota Kendari No. 6 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah",
  "Baubau": "Perda Kota Baubau No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/299988/perda-kota-bau-bau-no-1-tahun-2024",
  "Bombana": "Perda Kab. Bombana No. 6 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-bombana-no-6-tahun-2023",
  "Wakatobi": "Perda Kab. Wakatobi No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-wakatobi-no-1-tahun-2024",
  "Kolaka Utara": "Perda Kab. Kolaka Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/309230/perda-kab-kolaka-utara-no-1-tahun-2024",
  "Kolaka Timur": "Perda Kab. Kolaka Timur No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/300157/perda-kab-kolaka-timur-no-1-tahun-2024",
  "Kolaka": "Perda Kab. Kolaka No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah (perlu dipastikan)",
  "Konawe Selatan": "Perda Kab. Konawe Selatan No. 8 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/291609/perda-kab-konawe-selatan-no-8-tahun-2023",
  "Konawe Utara": "Perda Kab. Konawe Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/304190/perda-kab-konawe-utara-no-1-tahun-2024",
  "Konawe": "Perda Kab. Konawe No. 3 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-konawe-no-3-tahun-2023",
  "Buton Utara": "Perda Kab. Buton Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/278192/perda-kab-buton-utara-no-1-tahun-2024",
  "Buton Tengah": "Perda Kab. Buton Tengah No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-buton-tengah-no-1-tahun-2024",
  "Buton": "Perda Kab. Buton No. 6 Tahun 2023 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-buton-no-6-tahun-2023",
  "Muna": "Perda Kab. Muna No. 2 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/298899/perda-kab-muna-no-2-tahun-2024",
  "Kota Gorontalo": "Perda Kota Gorontalo No. 1 Tahun 2024 tentang Pajak dan Retribusi; sumber: https://peraturan.bpk.go.id/Details/284016/perda-kota-gorontalo-no-1-tahun-2024",
  "Gorontalo Utara": "Perda Kab. Gorontalo Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/283611/perda-kab-gorontalo-utara-no-1-tahun-2024",
  "Gorontalo": "Perda Kab. Gorontalo No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/313975/perda-kab-gorontalo-no-1-tahun-2024",
  "Boalemo": "Perda Kab. Boalemo No. 6 Tahun 2022 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/244513/perda-kab-boalemo-no-6-tahun-2022",
  "Bone Bolango": "Perda Kab. Bone Bolango No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/300225/perda-kab-bone-bolango-no-1-tahun-2024",
  "Manado": "Perda Kota Manado No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://perpajakan.ddtc.co.id/id/sumber-hukum/peraturan-daerah/perda-kota-manado-1-tahun-2024",
  "Bitung": "Perda Kota Bitung No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/308953/perda-kota-bitung-no-1-tahun-2024",
  "Tomohon": "Perda Kota Tomohon No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/311336/perda-kota-tomohon-no-1-tahun-2024",
  "Kotamobagu": "Perda Kota Kotamobagu No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/310060/perda-kota-kotamobagu-no-1-tahun-2024",
  "Minahasa Utara": "Perda Kab. Minahasa Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/311326/perda-kab-minahasa-utara-no-1-tahun-2024",
  "Minahasa Selatan": "Perda Kab. Minahasa Selatan No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/311272/perda-kab-minahasa-selatan-no-1-tahun-2024",
  "Minahasa Tenggara": "Perda Kab. Minahasa Tenggara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-minahasa-tenggara-1-2024",
  "Minahasa": "Perda Kab. Minahasa No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://peraturan.bpk.go.id/Details/310101/perda-kab-minahasa-no-1-tahun-2024",
  "Bolaang Mongondow Utara": "Perda Kab. Bolaang Mongondow Utara No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://jdih.bolmutkab.go.id/login/detailprodukhukum/5503",
  "Bolaang Mongondow Timur": "Perda Kab. Bolaang Mongondow Timur No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah; sumber: https://pasal.id/peraturan/perda/perda-kab-bolaang-mongondow-timur-1-2024",
  "Kepulauan Sangihe": "Perda Kab. Kepulauan Sangihe No. 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah (perlu dipastikan)"
};
